name: GitHub Actions - test
on:
  pull_request:

jobs:

  cpp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: srz-zumix/setup-infer@v1
      - name: infer
        run: |
          infer -- g++ -c example/cpp/test.cpp
      - uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review

  objc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: srz-zumix/setup-infer@v1
      - name: infer
        run: |
          infer -- clang -c example/cpp/test.cpp
      - uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
